## jetbrains/intellij-http-client
@Api_HostAddress = http://localhost:5101/category

### Get all categories
GET {{Api_HostAddress}}/

### Get category by ID
GET {{Api_HostAddress}}/{{CategoryId}}

### Create category
POST {{Api_HostAddress}}/
Content-Type: application/json

{
  "name": "{{$random.book.genre}}"
}

> {%
    client.global.set("category_id", response.body.CategoryId);
%}

### Update category
PUT {{Api_HostAddress}}/{{CategoryId}}
Content-Type: application/json

{
  "name": "{{CategoryName}}"
}

### Delete category
DELETE {{Api_HostAddress}}/{{CategoryId}}